experiment_name: "baseline_mlp"
project_name : "baseline_linear_relu_regression"

model:
  name: "baseline_model"
  type: "custom"
  layers:
    - flatten: true
    - linear: [512, 256]
    - activation: "relu"
    - linear: [256, 128]
    - activation: "relu"
    - linear: [128, 1] #we predict a single value because we have a regression task
  task: "regression"


training:
  num_epochs: 10
  batch_size: 64
  learning_rate: 0.001
  loss: "mean_squared_error"
  optimizer: "adam"