#a network that takes into account the discontinuities and the "circular" nature of the data
#we want to predict the sine and cosine of the angle (2 outputs)
#this is going to allow the model to see that 360 and 0 are actually the same thing

experiment_name: "newloss1"
project_name : "baseline_linear_relu_regression"

model:
  name: "newloss1_model"
  type: "custom" 
  layers:
    - flatten: true #not sure i need this
    - linear: [1568, 256]
    - activation: "tanh"
    - linear: [256, 128]
    - activation: "tanh"
    - linear: [128, 2] #we predict 2 values - sine and cosine of the angle
  task: "regression"
  use_sincos_encoding: true #this is going to tell the model to use sine and cosine encoding for the angle

training:
  num_epochs: 10
  batch_size: 64
  learning_rate: 0.001
  loss: "mse" #we still use mse as the loss function
  optimizer: "adam"