
experiment_name: "newloss2_angular_higherlr"
project_name : "baseline_linear_relu_regression"

model:
  name: "newloss2_angular_model"
  type: "custom" 
  layers:
    - flatten: true #not sure i need this
    - linear: [1568, 256]
    - activation: "tanh"
    - linear: [256, 128]
    - activation: "tanh"
    - linear: [128, 2] #we predict 2 values - sine and cosine of the angle
  task: "regression"
  use_sincos_encoding: true #this is going to tell the model to use sine and cosine encoding for the angle

training:
  num_epochs: 10
  batch_size: 64
  learning_rate: 0.01
  loss: "angular" #using the angular loss function to take into account the circular nature of the data
  optimizer: "adam"