#sine and cosine siamese network with angular loss function

experiment_name: "sincossiamese_angular"
project_name : "baseline_linear_relu_regression"

model:
  name: "sincossiamese_angular_model"
  type: "siamese" 
  embedding_layers:
    - flatten: true
    - linear: [784, 256]
    - activation: "relu"
    - linear: [256, 128]
    - activation: "relu"
  comparison_layers:
    - linear: [256, 128]
    - activation: "relu" 
    - linear: [128, 2] #we predict 2 values - sine and cosine of the angle
  task: "regression"
  use_sincos_encoding: true #this is going to tell the model to use sine and cosine encoding for the angle

training:
  num_epochs: 10
  batch_size: 64
  learning_rate: 0.001
  loss: "angular" #using the angular loss function to take into account the circular nature of the data
  optimizer: "adam"